### ISSUE TITLE
Upgrade to PyTorch 1.10

### ISSUE THREAD

**Issue by riveSunder** [riveSunder/yuca#1]
Advantages: 
* Faster CA simulation
Disadvantages:
* Changes the way objects/tensors are sent to devices

**Comment by riveSunder** [comment]
PyTorch 1.10.0 also plays differently with gradients. 
Errors when running `testing.test_all` with 1.10 (no errors with 1.5)
```
======================================================================
ERROR: test_multiverse_forward (testing.yuca.test_multiverse.TestCA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rlygr/Desktop/projects/yuca_readme/testing/yuca/test_multiverse.py", line 23, in test_multiverse_forward
    ca.to_device("cpu")
  File "/home/rlygr/Desktop/projects/yuca_readme/yuca/multiverse.py", line 873, in to_device
    param[:] = param.to(my_device)
RuntimeError: a view of a leaf Variable that requires grad is being used in an in-place operation.

======================================================================
ERROR: test_multiverse_to (testing.yuca.test_multiverse.TestCA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rlygr/Desktop/projects/yuca_readme/testing/yuca/test_multiverse.py", line 117, in test_multiverse_to
    ca.to_device(my_device)
  File "/home/rlygr/Desktop/projects/yuca_readme/yuca/multiverse.py", line 873, in to_device
    param[:] = param.to(my_device)
RuntimeError: a view of a leaf Variable that requires grad is being used in an in-place operation.

----------------------------------------------------------------------
Ran 8 tests in 1.570s

```

**Comment by riveSunder** [comment]
Should probably be `torch==1.11` now.

**Comment by riveSunder** [comment]
PyTorch version now updated to 2.0.1 in PR #58
